<footer class="page-footer font-small special-color-dark">
    <div class="footer-copyright text-sm-center text-black-50">
        <a class="text-dark" href="https://opensource.org/licenses/MIT">MIT License</a> - 2020 -
        <a class="text-dark" href="http://bugebo.exdrals.de"> bugebo.exdrals.de</a> - 
        <a class="text-dark" href="https://github.com/BibaltiK/bugebo"> @GitHUB</a>
    </div>
</footer>