<meta charset="UTF-8">    
<meta name="viewport" content="width=device-width, initial-scale=1">  
<link rel="stylesheet" type="text/css" media="screen" href="assets/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" media="screen" href="assets/css/fontawesome.min.css">    
<link rel="stylesheet" type="text/css" media="screen" href="assets/css/solid.min.css">    
<link rel="stylesheet" type="text/css" media="screen" href="assets/css/custom.css">
<title><?= $siteTitle ?></title>