<header class="sticky-top">
    <nav class="navbar  navbar-expand navbar-dark bg-dark">        
        <ul class="nav navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="/"><i class="fas fa-home"></i> <?= $home ?></a>
            </li>
        </ul> 
        <ul class="nav navbar-nav">            
            <li class="nav-item">
                <div class="nav-item dropdown ">
                    <?= $this->add('Navigation','switchLoginStatus'); ?>
                </div>
                
            </li>
        </ul>    
    </nav>
</header>   
