<div class="d-flex justify-content-center" style="padding-top: 3px">
    <button type="button" class="btn btn-loggedbar btn-loggedbar btn-sm"><i class="fas fa-list"></i> Übersicht</button>
    <div class="btn-group" role="group">
        <button type="button" class="btn btn-loggedbar btn-loggedbar-success btn-sm"><i class="fas fa-plus"></i> Einnahme</button>
        <button type="button" class="btn btn-loggedbar btn-loggedbar-danger btn-sm"><i class="fas fa-minus"></i> Ausgabe</button>
        <button type="button" class="btn btn-loggedbar btn-loggedbar-info btn-sm"><i class="fas fa-exchange-alt"></i> Umlagerung</button>

        <div class="btn-group" role="group">
        <div id="btnGroupDrop1" type="button" class="btn btn-sm btn-loggedbar dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="false" aria-expanded="true">
          Sonstiges
        </div>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="btnGroupDrop1">
          <a class="dropdown-item" href="#">Vorlagen</a>
          <a class="dropdown-item" href="#">Daueraufträge</a>
        </div>
        </div>
    </div>
</div>