<header class="sticky-top shadow">
    <nav class="navbar  navbar-expand navbar-dark bg-dark">        
        <ul class="nav navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="/"><i class="fas fa-home"></i><span class="text-sm"> <?= $home ?></span></a>
            </li>
        </ul> 
        <ul class="nav navbar-nav mr-auto ml-auto">
            <li class="nav-item">
                Hallo <?= $username ?>
            </li>
        </ul> 
        <ul class="nav navbar-nav">            
            <li class="nav-item">
                <div class="nav-item dropdown ">
                    <?= $this->insert($loginBar); ?>
                </div>
                
            </li>
        </ul>    
    </nav>
</header>   
