<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="false" aria-expanded="true" href="#"><i class="fas fa-user-cog"></i></a>
<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
    <a class="dropdown-item" href="#">Benutzereinstellungen</a>
    <a class="dropdown-item" href="#">Einstellungen</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="/logout">Abmelden</a>
</div>