<div class="d-flex justify-content-center" style="padding-top: 3px; padding-bottom: 20px">    
    <a class="btn btn-loggedbar btn-loggedbar btn-sm" href="/"><i class="fas fa-list"></i> Übersicht</a>
    <div class="btn-group" role="group">
        <a class="btn btn-loggedbar btn-loggedbar-success btn-sm" href="/transaction/payment/incoming"><i class="fas fa-plus"></i> Einnahme</a>        
        <a class="btn btn-loggedbar btn-loggedbar-danger btn-sm" href="/transaction/payment/outgoing"><i class="fas fa-minus"></i> Ausgabe</a>
        <a class="btn btn-loggedbar btn-loggedbar-info btn-sm" href="/transaction/payment/rearrangement"><i class="fas fa-exchange-alt"></i> Umlagerung</a>

        <div class="btn-group" role="group">
        <div id="btnGroupDrop1" type="button" class="btn btn-sm btn-loggedbar dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="false" aria-expanded="true">
          Sonstiges
        </div>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="btnGroupDrop1">
          <a class="dropdown-item" href="#">Vorlagen</a>
          <a class="dropdown-item" href="#">Daueraufträge</a>
        </div>
        </div>
    </div>
</div>