<a class="nav-link " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="false" aria-expanded="true" href="#"><i class="fas fa-user-lock"></i></a>
<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
    <div id="container" class="col-12">               
        
        <form id="login-form" class="form" action="/login" method="post">                        
            <div class="form-group">                
                <input type="text" name="username" id="username" class="form-control form-control-sm" placeholder="Benutzername">
            </div>
            <div class="form-group">
                <input type="text" name="password" id="password" class="form-control form-control-sm" placeholder="Passwort">
            </div>
            <div class="form-group">
                <label for="remember-me" id="remember-me-label">Angemeldet bleiben <input id="remember-me" name="remember-me" type="checkbox"></label>
            </div>
            <div class="form-group text-center">
                
                <input type="submit" name="submit" class="btn btn-success btn-sm" value="Anmelden">
            </div>
            <div id="register-link" class="text-center">
                <a href="#" class="text-dark">Registrieren</a>
            </div>
        </form>
        
    </div> 
</div>