<div class="d-flex justify-content-center" style="padding-top: 3px">
<div class="btn-group" role="group">
  <button type="button" class="btn btn-loggedbar btn-sm">1</button>
  <button type="button" class="btn btn-loggedbar btn-sm">2</button>

  <div class="btn-group" role="group">
    <button id="btnGroupDrop1" type="button" class="btn btn-sm btn-loggedbar dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Dropdown
    </button>
    <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
      <a class="dropdown-item" href="#">Dropdown link</a>
      <a class="dropdown-item" href="#">Dropdown link</a>
    </div>
  </div>
</div>
</div>