<!DOCTYPE html>
<html lang="en">
    <head>    

        <?= $this->insert('partials/head'); ?>

    </head>

    <body>   

        <?= $this->add('Navigation','top'); ?>  
        
        <?php if($hasFlashMessages):?>
            
              <div class="alert alert-danger text-center" role="alert">
                <?php foreach($flashMessages as $message):?>
                  <p><?= $message?></p>
                <?php endforeach?>
              </div>
            
        <?php endif;?>
        <main>
            <?= $content ?>
        </main>

        <?= $this->insert('partials/footer'); ?>

        <?= $this->insert('partials/scripts'); ?>

    </body>

</html>