<!DOCTYPE html>
<html lang="en">
    <head>    

        <?= $this->render('partials/head'); ?>

    </head>

    <body>   


        <?= $this->render('partials/navigation_top'); ?>

        <?= $this->render($loginActionBar); ?>
        
        <?= $this->render('partials/flashmessage'); ?>

        <main class="container" style="min-height: 500px">
            <?= $content ?>
        </main>
        <div style="min-height: 100px;"></div>

        <?= $this->render('partials/footer'); ?>

        <?= $this->render('partials/scripts'); ?>

    </body>

</html>