index:
    path:     /
    controller: 'Exdrals\Bugebo\Controller\Index::index' 


foo_route:
    path:     /foo
    controller: 'FooController::indexAction' 
 
foo_placeholder_route:
    path:     /foo/{id}
    controller: 'FooController::loadAction' 
    requirements:
        id: '[0-9]+'

foo_placeholder_route2:
    path:     /foo/{id}/{bla}
    controller: 'FooController::loadAction'
    requirements:
        id: '[0-9]+'
        bla: '[a-z,A-z]+'
