<!DOCTYPE html>
<html lang="en">
<head>    
    <meta charset="UTF-8">    
    <meta name="viewport" content="width=device-width, initial-scale=1">  
    <link rel="stylesheet" type="text/css" media="screen" href="assets/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href="assets/css/fontawesome.min.css">    
    <link rel="stylesheet" type="text/css" media="screen" href="assets/css/solid.min.css">    
    <link rel="stylesheet" type="text/css" media="screen" href="assets/css/custom.css">
    <title>Bugebo</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-icon-top navbar-expand navbar-dark bg-dark">                      
            <ul class="nav navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fas fa-home"></i></a>
                </li>

            </ul> 
            
            <ul class="nav navbar-nav">               
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fas fa-envelope-open"></i></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fas fa-user-cog"></i></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fas fa-tools"></i></a>
                </li>
            </ul>
        </nav>
    </header>
    
    <main>
        Content
    </main>
    
    <footer class="page-footer font-small special-color-dark">
        <div class="footer-copyright text-center py-3"><a href="https://opensource.org/licenses/MIT">MIT License</a> - 2020 -
            <a href="http://bugebo.exdrals.de"> bugebo.exdrals.de</a>
        </div>
    </footer>
<!--
    <script src="assets/js/jquery-3.5.1.min.js"></script>
    <script src="assets/js/popper.min.js"></script>
-->
    <script src="assets/js/bootstrap.min.js"></script>    
</body>
</html>